- name: Install nginx
  hosts: local
  connection: local
 
  become: yes
  tasks:
    - name: Install nginx if RedHat based system
      ansible.builtin.dnf:
        name: nginx
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
     