- name: variables
  hosts: local
  connection: local
  vars:
  COURSE: "Ansible"
  TRAINER: "Mounika"


  message: "Hello, Ansible!"
  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: HELLO all, welcome to {{ COURSE }} training by {{ TRAINER }}. {{ message }}