- name: variables
  hosts: local
  connection: local
  vars:
   COURSE: "Ansible"
   TRAINER: "Mounika"
  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: HELLO all, welcome to {{ COURSE }} course training by {{ TRAINER }}. 